// <auto-generated />
using System;
using GrpcService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrpcService.Migrations
{
    [DbContext(typeof(AkteDbContext))]
    [Migration("20210921151306_AddsVorgang")]
    partial class AddsVorgang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("GrpcService.Models.Akte", b =>
                {
                    b.Property<Guid>("AktenNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("AktenNummer");

                    b.HasIndex("Name");

                    b.ToTable("Akten");
                });

            modelBuilder.Entity("GrpcService.Models.Vorgang", b =>
                {
                    b.Property<Guid>("VorangsNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AktenNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("VorangsNummer");

                    b.HasIndex("AktenNummer");

                    b.ToTable("Vorgaenge");
                });

            modelBuilder.Entity("GrpcService.Models.Vorgang", b =>
                {
                    b.HasOne("GrpcService.Models.Akte", null)
                        .WithMany("Vorgaenge")
                        .HasForeignKey("AktenNummer");
                });

            modelBuilder.Entity("GrpcService.Models.Akte", b =>
                {
                    b.Navigation("Vorgaenge");
                });
#pragma warning restore 612, 618
        }
    }
}
